# Generated by Django 4.0.2 on 2022-02-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click above to read post', max_length=500),
        ),
    ]
